

version: '3'
services:

  sqlserver:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "mssql1Ipw"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    networks:
      - crm-compose-network
    volumes:
      - ./SimpleCRM-API/mssql:/mssql

  mssqltools:
    image: mcr.microsoft.com/mssql-tools
    environment:
      HOST: "sqlserver"
      USERNAME: "sa"
      PASSWORD: "mssql1Ipw"
      DATABASE: "SimpleCRM"
    depends_on:
      - sqlserver
    command: /opt/mssql-tools/bin/sqlcmd -S $HOST -U $USERNAME -P $PASSWORD -Q "RESTORE DATABASE ${DATABASE}  FROM  DISK='/mssql/db.bkp'"
    networks:
      - crm-compose-network

  front: 
    build: ./Simple-CRM-FRONT
    container_name: front-end
    ports:
      - "8000:80"
    networks:
      - crm-compose-network
    depends_on:
      - api
      
  api:
    container_name: api
    build:
      context: ./SimpleCRM-API
    ports:
      - 3000:3000
    environment:
      HOST: "sqlserver"
      PORT: 1433
      USERNAME: "sa"
      PASSWORD: "mssql1Ipw"
      DATABASE: "SimpleCRM"
      SECRET_KEY: "vCpl8LAm0q"
      EXPIRATION_TOKEN: 3600
    depends_on:
      - sqlserver
    networks:
      - crm-compose-network


networks: 
  crm-compose-network:
    driver: bridge